import type { LivePlan, LoaderTrip } from './types';

/** Replace with SQLite reads once loader sync is wired. Shapes match the future API. */
export const livePlan: LivePlan = {
  revision: 2,
  updatedAt: '22:10 IST',
  facility: 'Peliyagoda Central Depot',
  activeDocks: 'Bay B-04 / B-08',
};

export const trips: LoaderTrip[] = [
  {
    id: 'trip-veh018',
    vehicleCode: 'VEH018',
    tripNo: 1,
    category: 'fresh',
    vehicleType: 'Reefer Truck',
    route: 'Colombo Route',
    departsAt: '03:30',
    minutesToDeparture: 42,
    stopsLoaded: 5,
    totalStops: 7,
    payloadKg: 1820,
    volumeM3: 14.4,
    dock: 'Dock Bay B-04',
  },
  {
    id: 'trip-veh022',
    vehicleCode: 'VEH022',
    tripNo: 2,
    category: 'fresh',
    vehicleType: 'Chilled Van',
    route: null,
    departsAt: '04:15',
    minutesToDeparture: 87,
    stopsLoaded: 0,
    totalStops: 6,
    payloadKg: 960,
    volumeM3: 8.2,
    dock: 'Dock Bay B-07',
    planUpdate: { revision: 3, message: '+1 priority order re-assigned from VEH018' },
  },
  {
    id: 'trip-veh031',
    vehicleCode: 'VEH031',
    tripNo: 1,
    category: 'style',
    vehicleType: 'Box Truck',
    route: 'Kandy Route',
    departsAt: '05:00',
    minutesToDeparture: 132,
    stopsLoaded: 0,
    totalStops: 5,
    payloadKg: 1240,
    volumeM3: 11.0,
    dock: 'Dock Bay B-08',
  },
  {
    id: 'trip-veh040',
    vehicleCode: 'VEH040',
    tripNo: 1,
    category: 'tech',
    vehicleType: 'Panel Van',
    route: 'Galle Route',
    departsAt: '05:45',
    minutesToDeparture: 177,
    stopsLoaded: 0,
    totalStops: 4,
    payloadKg: 540,
    volumeM3: 5.6,
    dock: 'Dock Bay B-09',
  },
];